// <auto-generated />
using JobSearching.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JobSearching.Data.Migrations
{
    [DbContext(typeof(JobSearchingDbContext))]
    [Migration("20190725144138_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JobSearching.Data.Models.Employer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("age");

                    b.Property<string>("companyName");

                    b.Property<string>("contactEmail");

                    b.Property<string>("contactPhone");

                    b.Property<string>("currentAddress");

                    b.Property<string>("firstName");

                    b.Property<string>("lastName");

                    b.Property<string>("middleName");

                    b.HasKey("id");

                    b.ToTable("Employers");
                });

            modelBuilder.Entity("JobSearching.Data.Models.JobAd", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("description");

                    b.Property<string>("employerId");

                    b.Property<string>("positionName");

                    b.HasKey("id");

                    b.ToTable("JobAds");
                });

            modelBuilder.Entity("JobSearching.Data.Models.JobVolunteer", b =>
                {
                    b.Property<int>("JobAdId");

                    b.Property<int>("VolunteerId");

                    b.HasKey("JobAdId", "VolunteerId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("JobVolunteer");
                });

            modelBuilder.Entity("JobSearching.Data.Models.Volunteer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("age");

                    b.Property<string>("contactInformation");

                    b.Property<string>("firstName");

                    b.Property<string>("lastName");

                    b.Property<string>("password");

                    b.Property<string>("username");

                    b.HasKey("id");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("JobSearching.Data.Models.JobVolunteer", b =>
                {
                    b.HasOne("JobSearching.Data.Models.JobAd", "JobAd")
                        .WithMany("Volunteers")
                        .HasForeignKey("JobAdId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JobSearching.Data.Models.Volunteer", "Volunteer")
                        .WithMany("JobAds")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
