// <auto-generated />
using System;
using JobSearching.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JobSearching.Data.Migrations
{
    [DbContext(typeof(JobSearchingDbContext))]
    partial class JobSearchingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JobSearching.Data.Models.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("CompanyName");

                    b.Property<string>("ContactEmail");

                    b.Property<string>("ContactPhone");

                    b.Property<string>("CurrentAddress");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("MiddleName");

                    b.Property<DateTime>("RegisteredOn");

                    b.HasKey("Id");

                    b.ToTable("Employers");
                });

            modelBuilder.Entity("JobSearching.Data.Models.JobAd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("EmployerId");

                    b.Property<string>("PositionName");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.ToTable("JobAds");
                });

            modelBuilder.Entity("JobSearching.Data.Models.JobVolunteer", b =>
                {
                    b.Property<int>("JobAdId");

                    b.Property<int>("VolunteerId");

                    b.HasKey("JobAdId", "VolunteerId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("JobVolunteer");
                });

            modelBuilder.Entity("JobSearching.Data.Models.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("ContactInformation");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<DateTime>("RegisteredOn");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("JobSearching.Data.Models.JobAd", b =>
                {
                    b.HasOne("JobSearching.Data.Models.Employer", "Employer")
                        .WithMany("JobAds")
                        .HasForeignKey("EmployerId")
                        .HasConstraintName("FK_JobAd_Employer")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobSearching.Data.Models.JobVolunteer", b =>
                {
                    b.HasOne("JobSearching.Data.Models.JobAd", "JobAd")
                        .WithMany("Volunteers")
                        .HasForeignKey("JobAdId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JobSearching.Data.Models.Volunteer", "Volunteer")
                        .WithMany("JobAds")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
